#!/usr/bin/env bash
#
# BSSG - Site Initialization Script
# Initializes a new, separate site directory structure.
#

set -e

# Terminal colors (copied for standalone use if needed, but should be sourced)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
NC='\033[0m' # No Color

# --- Configuration ---
# Get the directory where BSSG core scripts are located
BSSG_CORE_DIR=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
CORE_CONFIG_LOCAL="$BSSG_CORE_DIR/config.sh.local"

# --- Argument Validation ---
TARGET_DIR="$1"
if [ -z "$TARGET_DIR" ]; then
    echo -e "${RED}Error: Target directory argument is required.${NC}"
    echo -e "Usage: ./bssg.sh init <target_directory>"
    exit 1
fi

# --- Directory Setup ---
echo -e "${YELLOW}Initializing new BSSG site structure in '$TARGET_DIR'...${NC}"

# Ensure target directory exists
mkdir -p "$TARGET_DIR"

# Get absolute path for the target directory
TARGET_ABS_PATH=$(cd "$TARGET_DIR" && pwd)
echo "Absolute path for site: $TARGET_ABS_PATH"

# Define subdirectories
SITE_SRC_DIR="$TARGET_ABS_PATH/src"
SITE_PAGES_DIR="$TARGET_ABS_PATH/pages"
SITE_DRAFTS_DIR="$TARGET_ABS_PATH/drafts"
SITE_STATIC_DIR="$TARGET_ABS_PATH/static"
SITE_OUTPUT_DIR="$TARGET_ABS_PATH/output" # Define output dir for the site

# Create subdirectories
echo "Creating directories..."
mkdir -p "$SITE_SRC_DIR"
mkdir -p "$SITE_PAGES_DIR"
mkdir -p "$SITE_DRAFTS_DIR"
mkdir -p "$SITE_DRAFTS_DIR/pages" # Subdir for page drafts
mkdir -p "$SITE_STATIC_DIR"
# No need to create output dir here, build process handles it
echo -e "${GREEN}Directory structure created successfully.${NC}"

# --- Site Config Generation ---
SITE_CONFIG_LOCAL="$TARGET_ABS_PATH/config.sh.local"
echo "Generating site-specific config file: $SITE_CONFIG_LOCAL"

# Create config content
# Note: We explicitly use absolute paths here
# We DO NOT define TEMPLATES_DIR or THEMES_DIR, allowing them to be sourced
# from the core config.sh (or its core config.sh.local override).
cat > "$SITE_CONFIG_LOCAL" << EOF
#!/usr/bin/env bash
#
# Local configuration for BSSG site at $TARGET_ABS_PATH
# Generated by: bssg init
#

# --- Content Directories (Absolute Paths) ---
SRC_DIR="$SITE_SRC_DIR"
PAGES_DIR="$SITE_PAGES_DIR"
DRAFTS_DIR="$SITE_DRAFTS_DIR"
STATIC_DIR="$SITE_STATIC_DIR"
OUTPUT_DIR="$SITE_OUTPUT_DIR" # Site output directory

# --- Site Specific Overrides (Examples) ---
# SITE_TITLE="My New Site"
# SITE_URL="http://example.com"
# THEME="dark" # Optional: override theme just for this site

EOF

echo -e "${GREEN}Site config '$SITE_CONFIG_LOCAL' created.${NC}"

# --- Core Config Sourcing (Optional) ---
echo
echo -e "${YELLOW}Optional: Automatically load this site's config?${NC}"
echo "This will modify '$CORE_CONFIG_LOCAL' in your BSSG installation directory."
echo "It will add a line to source '$SITE_CONFIG_LOCAL' whenever you run ./bssg.sh from the core directory."
echo "This avoids needing to specify '--config $SITE_CONFIG_LOCAL' for every build."

read -p "Modify '$CORE_CONFIG_LOCAL' to source the new site config? (y/N): " confirm </dev/tty

if [[ "$confirm" == "y" || "$confirm" == "Y" ]]; then
    echo "Modifying core config: $CORE_CONFIG_LOCAL" 
    
    # Create the core config.sh.local if it doesn't exist
    if [ ! -f "$CORE_CONFIG_LOCAL" ]; then
        echo "#!/usr/bin/env bash" > "$CORE_CONFIG_LOCAL"
        echo "# BSSG Core Local Configuration Overrides" >> "$CORE_CONFIG_LOCAL"
        echo "Created $CORE_CONFIG_LOCAL."
    fi
    
    # Check if the source line already exists
    if grep -Fxq "source \"$SITE_CONFIG_LOCAL\"" "$CORE_CONFIG_LOCAL"; then
        echo "Source line already exists in $CORE_CONFIG_LOCAL. No changes needed."
    else
        # Append the source line
        echo "" >> "$CORE_CONFIG_LOCAL" # Add a newline for separation
        echo "# Source site-specific config for: $TARGET_ABS_PATH" >> "$CORE_CONFIG_LOCAL"
        echo "source \"$SITE_CONFIG_LOCAL\"" >> "$CORE_CONFIG_LOCAL"
        echo -e "${GREEN}Successfully added source line to $CORE_CONFIG_LOCAL.${NC}"
    fi
else
    echo "Skipping modification of core config."
    echo "To use this site, run BSSG commands with the --config flag:"
    echo "  ./bssg.sh build --config $SITE_CONFIG_LOCAL"
fi

echo
echo -e "${GREEN}Site initialization complete in '$TARGET_ABS_PATH'.${NC}" 